describe('Window Handle',() => {
    xit('Child Window test',() => {
        browser.url('https://rahulshettyacademy.com/AutomationPractice/')
        $('#openwindow').click()
        browser.pause(3000)
        var windows = browser.getWindowHandles()
        console.log(windows[1])
        browser.switchToWindow(windows[1])
        console.log(browser.getTitle())
        browser.closeWindow()
        browser.switchToWindow(windows[0])
        console.log(browser.getTitle())
        browser.newWindow('https://rahulshettyacademy.com/#/index')
        let title = browser.getTitle()
        browser.switchWindow('https://rahulshettyacademy.com/AutomationPractice/')
        $('#name').setValue(title)
        browser.pause(3000)
        browser.switchWindow(title)
        console.log(browser.getUrl())
    })
})